VLTApplication/VLTApplication/Controllers/VLTeaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VLTApplication.Models;
using System.Transactions;
namespace VLTApplication.Controllers
{
    public class VLTeaController : Controller
    {
        CS4PEntities db = new CS4PEntities();
        public ActionResult Index()
        {
            var model = db.BubleTeas;
            return View(model.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BubleTea model)
        {
            ValidateBubleTea(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    //add model to db
                    db.BubleTeas.Add(model);
                    db.SaveChanges();

                    //save file to app_data
                    var path = Server.MapPath("~/App_Data");
                    path = System.IO.Path.Combine(path, model.id.ToString());
                    Request.Files["Image"].SaveAs(path);
                    // all done successfully.
                    scope.Complete();
                    return RedirectToAction("Index");
                }
                
            }
            return View(model);
        }

        public ActionResult Image (string id)
        {
            var path = Server.MapPath("~/App_Data");
            path = System.IO.Path.Combine(path, id);
            return File(path, "image/*");
        }

        private void ValidateBubleTea(BubleTea model)
        {
            if (model.Price <= 0)
                ModelState.AddModelError("Price", VLTError.PRICE_LESS_0);
        }

        public ActionResult Edit(int id)
        {
            var model = db.BubleTeas.Find(id);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(BubleTea model)
        {
            ValidateBubleTea(model);
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var model = db.BubleTeas.Find(id);
            if (model == null)
                return HttpNotFound();
            db.BubleTeas.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
	}
}

VLTApplication/VLTApplication/Views/VLTea/Create.cshtml
@model BubleTea

@{
    ViewBag.Title = "Create";
}

<h2>Them mon moi</h2>


@using (Html.BeginForm("Create", "VLTea", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tra sua</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Ten goi", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Topping, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topping)
                @Html.ValidationMessageFor(model => model.Topping)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Gia tien", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            <label for="1339" class="control-label col-md-2">Hinh anh</label>
            <div class="col-md-10">
                <input type="file" name="Image" id="1339" onchange="readIMG(this)" />
                <img id="Demo" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Them moi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readIMG(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#Demo')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

VLTApplication/VLTApplication/Views/VLTea/Index.cshtml
@model IEnumerable<BubleTea>

@{
    ViewBag.Title = "Index";
}

<h2>Tra sua Van Lang</h2>

<p>
    <a href="@Url.Action("Create")">Them moi</a>
</p>
<table class="table">
    <tr>
        <th>
            Tra sua
        </th>
        <th>
            Chi tiet
        </th>
        <th>
            Gia tien
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <mark>@item.Name</mark>
        </td>
        <td>
            @item.Topping
        </td>
        <td>
            @item.Price.ToString("N0")
        </td>
        <td>
            <img src="@Url.Action("Image", new { id = item.id})" />
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id = item.id })">Sua</a> |
            <a href="@Url.Action("Details", new { id = item.id })">Xem</a> |
            <a href="@Url.Action("Delete", new { id = item.id })">Xoa</a>
        </td>
    </tr>
}

</table>